# Characters file
import pygame
import color


class Monster:

    def yetiRun(self, screen, x, y):
        size = 1
        width = 25
        heigth = 43
        tilemap = [[color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.colorKey,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.black,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.red,color.grayLight,color.red,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.yellow,color.black,color.yellow,color.black,color.yellow,color.black,color.yellow,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.yellow,color.black,color.yellow,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.black,color.black,color.black,color.black,color.black,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.black,color.black,color.grayLight,color.black,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.black,color.grayLight,color.grayLight,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.black,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.black,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.black,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.black,color.black],
                   [color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.colorKey,color.black],
                   [color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.black],
                   [color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.black,color.black,color.colorKey],
                   [color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.colorKey,color.colorKey],
                   [color.colorKey,color.black,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.black,color.grayLight,color.grayLight,color.black,color.black,color.grayLight,color.black,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.black,color.black,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.black,color.colorKey,color.colorKey,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey]
                   ]
        for row in range(heigth):
            for column in range(width):
                pygame.draw.rect(screen, tilemap[row][column], (column*size,row*size,size,size))

    def yetiCelebrate(self, screen, x, y):
        size = 1
        width = 32
        heigth =  40
        tilemap = [[color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey],
                   [color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.black,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.black,color.grayLight,color.black,color.black,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.red,color.grayLight,color.red,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.black],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.black,color.yellow,color.black,color.yellow,color.black,color.yellow,color.black,color.yellow,color.black,color.colorKey,color.colorKey,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.black,color.black,color.black,color.yellow,color.black,color.yellow,color.black,color.black,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.black,color.grayLight,color.black,color.black,color.black,color.black,color.black,color.grayLight,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.black,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.black,color.grayLight,color.grayLight,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey]
                   ]
        for row in range(heigth):
            for column in range(width):
                pygame.draw.rect(screen, tilemap[row][column], (column * size, row * size, size, size))


    def yetiEating1(self, screen, x, y):
        size = 1
        width = 29
        heigth = 41
        tilemap = [[color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.red,color.red,color.red,color.red,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.red,color.red,color.red,color.red,color.red,color.red,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.grayLight,color.red,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.red,color.red,color.red,color.red,color.red,color.red,color.red,color.red],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.red,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.red,color.red,color.red,color.red,color.red,color.red,color.red,color.red],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.blue,color.blue,color.blue,color.blue,color.blue,color.colorKey,color.red,color.red],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.beige,color.blue,color.blue,color.beige,color.beige,color.beige,color.blue,color.colorKey,color.red],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.black,color.black,color.yellow,color.black,color.yellow,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.beige,color.beige,color.beige,color.beige,color.beige,color.beige,color.beige,color.black,color.colorKey,color.red],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.yellow,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.beige,color.beige,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.beige,color.beige,color.beige,color.beige,color.black,color.black,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.red,color.red,color.red,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.beige,color.beige,color.beige,color.beige,color.black,color.black,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.red,color.red,color.magenta,color.magenta,color.magenta,color.magenta,color.magenta,color.magenta,color.azure,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.yellow,color.black,color.black,color.black,color.black,color.black,color.red,color.magenta,color.magenta,color.magenta,color.magenta,color.magenta,color.black,color.azure,color.azure,color.azure,color.azure,color.azure,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.black,color.black,color.yellow,color.black,color.yellow,color.black,color.colorKey,color.colorKey,color.colorKey,color.magenta,color.black,color.black,color.azure,color.azure,color.azure,color.magenta,color.magenta,color.azure,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.red,color.black,color.colorKey,color.colorKey,color.azure,color.azure,color.magenta,color.magenta,color.magenta,color.azure,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.red,color.red,color.magenta,color.colorKey,color.colorKey,color.azure,color.magenta,color.magenta,color.magenta,color.magenta,color.azure,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.red,color.magenta,color.magenta,color.magenta,color.magenta,color.magenta,color.magenta,color.magenta,color.magenta,color.azure,color.azure,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.magenta,color.magenta,color.magenta,color.magenta,color.magenta,color.magenta,color.magenta,color.azure,color.azure,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.magenta,color.magenta,color.black,color.azure,color.azure,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.azure,color.azure,color.azure,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.azure,color.black,color.azure,color.azure,color.azure,color.azure,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.azure,color.azure,color.azure,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.azure,color.azure,color.azure,color.azure,color.azure,color.azure,color.blue,color.blue,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.azure,color.azure,color.azure,color.azure,color.azure,color.blue,color.blue,color.blue,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.azure,color.azure,color.azure,color.azure,color.blue,color.blue,color.blue,color.blue,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.greenDark,color.greenDark,color.greenDark,color.azure,color.azure,color.azure,color.azure,color.colorKey,color.blue,color.blue,color.blue,color.blue,color.blue,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.greenDark,color.greenDark,color.greenDark,color.azure,color.azure,color.colorKey,color.colorKey,color.colorKey,color.blue,color.blue,color.blue,color.greenDark,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.greenDark,color.greenDark,color.greenDark,color.greenDark,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.blue,color.blue,color.greenDark,color.greenDark,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.greenDark,color.greenDark,color.greenDark,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.blue,color.greenDark,color.greenDark,color.greenDark,color.colorKey,color.colorKey,color.black],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.greenDark,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.greenDark,color.greenDark,color.greenDark,color.greenDark,color.black,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.greenDark,color.greenDark,color.greenDark,color.greenDark,color.black,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.greenDark,color.greenDark,color.greenDark,color.black,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.greenDark,color.greenDark,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.black,color.black,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.black,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey]
                   ]
        for row in range(heigth):
            for column in range(width):
                pygame.draw.rect(screen, tilemap[row][column], (column * size, row * size, size, size))

    def yetiEating2(self, screen, x, y):
        size = 1
        width = 23
        heigth = 41
        tilemap = [[color.colorKey,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.greenDark,color.greenDark,color.greenDark,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.black],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.colorKey,color.greenDark,color.greenDark,color.greenDark,color.greenDark,color.greenDark,color.greenDark,color.greenDark,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black],
                   [color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.greenDark,color.greenDark,color.greenDark,color.greenDark,color.greenDark,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.greenDark,color.greenDark,color.greenDark,color.greenDark,color.greenDark,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.black,color.azure,color.azure,color.azure,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.grayLight,color.black,color.yellow,color.black,color.azure,color.azure,color.azure,color.black,color.yellow,color.black,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.black,color.black,color.red,color.grayLight,color.grayLight,color.black,color.black,color.black,color.azure,color.azure,color.azure,color.black,color.black,color.black,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.yellow,color.black,color.azure,color.azure,color.azure,color.black,color.yellow,color.black,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.black,color.red,color.grayLight,color.black,color.black,color.black,color.black,color.azure,color.black,color.black,color.black,color.black,color.black,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.yellow,color.black,color.azure,color.black,color.yellow,color.black,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.black,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.black,color.grayLight,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black],
                   [color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey],
                   [color.black,color.black,color.colorKey,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey],
                   [color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey]
                   ]
        for row in range(heigth):
            for column in range(width):
                pygame.draw.rect(screen, tilemap[row][column], (column * size, row * size, size, size))

    def yetiEating3(self, screen, x, y):
        size = 1
        width = 26
        heigth = 37
        tilemap = [[color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.black,color.grayLight,color.black,color.black,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.red,color.grayLight,color.red,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.yellow,color.black,color.yellow,color.black,color.yellow,color.black,color.yellow,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.yellow,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.black,color.black,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.colorKey,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.black,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.black,color.black,color.grayLight,color.grayLight,color.black,color.colorKey,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.black,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.black,color.black,color.black,color.colorKey],
                   [color.colorKey,color.black,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black],
                   [color.black,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey],
                   [color.colorKey,color.black,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.grayLight,color.black,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.black,color.black,color.black,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.black,color.black,color.black,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.black,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.grayLight,color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.black,color.black,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.colorKey,color.black,color.black,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.black,color.black,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   [color.colorKey,color.black,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.black,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey,color.colorKey],
                   ]
        for row in range(heigth):
            for column in range(width):
                pygame.draw.rect(screen, tilemap[row][column], (column * size, row * size, size, size))